<?php 
return array(
	"access" => "accès",
	"~access ~denied" => "~accès ~refusé",
	"~access ~rights" => "~droits d'~accès",
	"~add ~user" => "~ajouter un ~utilisateur",
	"~assign/~unassign ~rights to ~users"=>"~assigner/~désassigner des ~droits aux ~utilisateurs",		
	"~assign/~unassign ~roles to ~users"=>"~assigner/~désassigner des ~rôles aux ~utilisateurs",		
	"~attached ~to ~user" => "~attaché ~à l'~utilisateur",
	"domain"=>"domaine",
	"~inherited ~from ~roles" => "~hérité ~des ~rôles",
	"login"=>"s'identifier",
	"~manage ~roles (create/remove/edit)"=>"~gérer les ~rôles (créer/supprimer/éditer)",
	"password"=>"mot de passe",
	"right"=>"droit",
	"role"=>"rôle",
	"roles"=>"rôles",
	"~see ~rights of a ~user"=>"~voir les ~droits de l'~utilisateur",
	"~see ~roles of a ~user"=>"~voir les ~rôles de l'~utilisateur",
	"~see the ~list of ~users"=>"~voir la ~liste des ~utilisateurs",
	"user"=>"utilisateur",
	"~users ~list" => "~liste des ~utilisateurs",
	"~user ~management" => "~gestion des ~utilisateurs", 
	"~user ~rights" => "~droits de l'~utilisateur", 
	"username"=>"identifiant",
		
	"This user is an administrator, it has the right to do everything"=>"Cet utilisateur est un administrateur, il a le droit de faire ce qu'il veut",
);
?>