<?php 
return array(
	"access" => "access",
	"~access ~denied" => "~access ~denied",
	"~access ~rights" => "~access ~rights",
	"~assign/~unassign ~rights to ~users"=>"~assign/~unassign ~rights to ~users",
	"~assign/~unassign ~roles to ~users"=>"~assign/~unassign ~roles to ~users",
	"~add ~user" => "~add ~user",
	"~attached ~to ~user" => "~attached ~to ~user",
	"domain"=>"domain",
	"~inherited ~from ~roles" => "~inherited ~from ~roles",
	"login"=>"login",
	"~manage ~roles (create/remove/edit)"=>"~manage ~roles (create/remove/edit)",
	"password"=>"password",
	"right"=>"right",
	"role"=>"role",
	"roles"=>"roles",
	"~see ~rights of a ~user"=>"~see ~rights of a ~user",
	"~see ~roles of a ~user"=>"~see ~roles of a ~user",
	"~see the ~list of ~users"=>"~see the ~list of ~users",
	"user"=>"user",
	"~users ~list" => "~users ~list",
	"~user ~management" => "~user ~management", 
	"~user ~rights" => "~user ~rights", 
	"username"=>"username",
		
	"This user is an administrator, it has the right to do everything"=>"This user is an administrator, it has the right to do everything",
);
?>