<?php 
return array(
	"curricula" => "programmes de formation", 
	"curriculum" => "programme de formation", 
	"~curriculum ~name" => "~nom du ~programme", 
	"~new ~curriculum" => "~nouveau ~programme",

	"~consult ~curricula" => "~consulter les ~programmes",
	"~edit ~curricula" => "~éditer les ~programmes",

	"cannot be empty" => "ne peut pas être vide",
	"this curriculum already exists" => "ce programme existe déjà",
);
?>