<?php
return array(
	"create a new curriculum" => "créer un nouveau programme",
	"create branch" => "créer une branche",
	"create root branch" => "créer une branche à la racine",
	"curricula" => "programmes de formation",
	"curriculum" => "programme de formation",
	"~curriculum ~name" => "~nom du ~programme",
	"from existing one" => "à partir d'un existant",
	"from scratch" => "vide",
	"~new ~curriculum" => "~nouveau ~programme",

	"~consult ~curricula" => "~consulter les ~programmes",
	"~edit ~curricula" => "~éditer les ~programmes",
);
?>