<?php 
return array(
	"create a new curriculum" => "create a new curriculum", 
	"curricula" => "curricula", 
	"curriculum" => "curriculum", 
	"~curriculum ~name" => "~curriculum ~name", 
	"from existing one" => "from existing one", 
	"from scratch" => "from scratch",
	"~new ~curriculum" => "~new ~curriculum",
		
	"~consult ~curricula" => "~consult ~curricula",
	"~edit ~curricula" => "~edit ~curricula",
);
?>