<?php 
return array(
	"~birth ~date" => "~date de ~naissance", 
	"people" => "personnes",
	"profile" => "profil",
	"~edit ~personal ~information" => "~éditer les ~informations ~personelles",
	"see other people personal information" => "voir les informations personelles des autres",
	"~personal ~information" => "~information ~personelle",
	"~first ~name" => "~prénom",
	"~last ~name" => "~nom de ~famille",
	"sex" => "sexe",
		
	"name cannot be empty" => "un nom ne peut pas être vide",
);
?>