<?php 
return array(
	"~birth ~date" => "~birth ~date", 
	"people" => "people",
	"profile" => "profile",
	"~edit ~personal ~information" => "~edit ~personal ~information",
	"see other people personal information" => "see other people personal information",
	"~personal ~information" => "~personal ~information",
	"~first ~name" => "~first ~name",
	"~last ~name" => "~last ~name",
	"sex" => "sex",
		
	"name cannot be empty" => "name cannot be empty",
);
?>