<?php 
return array(
	"database" => "database",
	"~loading ~application" => "~loading ~application", 
	"logout" => "logout",
	"inactivity" => "inactivity",
	"no result found for your search" => "no result found for your search",
	"results found" => "result(s) found",
		
	"january" => "january",
	"february" => "february",
	"march" => "march",
	"april" => "april",
	"may" => "may",
	"june" => "june",
	"july" => "july",
	"august" => "august",
	"september" => "september",
	"october" => "october",
	"november" => "november",
	"december" => "december",
);
?>