<?php 
return array(
	"add" => "ajouter",
	"cancel" => "annuler",
	"next" => "suivant",
	"ok" => "ok",
	"previous" => "précédant",
	"remove" => "supprimer",
	"save" => "enregistrer",
	"saving" => "enregistrement",

	"january" => "janvier",
	"february" => "février",
	"march" => "mars",
	"april" => "avril",
	"may" => "mai",
	"june" => "juin",
	"july" => "juillet",
	"august" => "août",
	"september" => "septembre",
	"october" => "octobre",
	"november" => "novembre",
	"december" => "décembre",
		
	"this data is already locked by" => "cette donnée est déjà vérouillée par", 
	"this page is already locked by" => "cette page est déjà vérouillée par", 
);
?>