<?php 
return array(
	"add" => "add",
	"cancel" => "cancel",
	"next" => "next",
	"ok" => "ok",
	"previous" => "previous",
	"remove" => "remove",
	"save" => "save",
	"saving" => "saving",

	"january" => "january",
	"february" => "february",
	"march" => "march",
	"april" => "april",
	"may" => "may",
	"june" => "june",
	"july" => "july",
	"august" => "august",
	"september" => "september",
	"october" => "october",
	"november" => "november",
	"december" => "december",
		
	"this data is already locked by" => "this data is already locked by", 
	"this page is already locked by" => "this page is already locked by", 
);
?>